data:
  batch_size: 128
  name: cifar100
  num_workers: 4
  split:
  - 0.9
  - 0.1
model:
  adaptive: false
  architecture: resnet34
  lr: 0.1
  momentum: 0
  name: sam
  nesterov: false
  rho: 0.05
  weight_decay: 0.001
trainer:
  epochs: 200
  sch: diminish1
  seed: 42
wandb:
  name: resnet34_diminish1_seed42
  project: Fundamental-SAM-CIFAR100-M0
