data:
  batch_size: 128
  name: tiny_imagenet
  num_workers: 4
  split:
  - 0.9
  - 0.1
model:
  adaptive: false
  architecture: resnet18
  lr: 0.1
  momentum: 0
  name: sam
  nesterov: false
  rho: 0.05
  weight_decay: 0.001
trainer:
  epochs: 200
  factor: 1
  sch: diminish1
  seed: 42
  total_iters: 200
wandb:
  name: resnet18_sam_diminish1_seed42
  project: Fundamental-SAM-TINY-IMAGENET1-M0
